baseURL: "/"
languageCode: en-us
title: bdverse
theme: "hugo-fresh"
relativeurls: true
publishDir: "docs"

params:
  navbarlogo:
  # Logo (from static/images/logos/___)
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: ""
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: bddwc
    url: /bddwc
  - title: bdchecks
    url: /bdchecks
  - title: bdclean
    url: /bdclean
  - title: bdvis
    url: /bdvis
  - title: bdtools
    url: /bdtools
  - title: Resources
    sublinks:
    - title: User Guide
      url: https://bd-r.github.io/bdverse-user-guide/
      blank: true
    - title: Developer Guide
      url: https://bd-r.github.io/bdverse-dev-guide/
      blank: true
    - title: Publications
      url: /publications
      blank: false
    - title: GitHub
      url: https://github.com/bd-R
      blank: true
  - title: About
    sublinks:
    - title: The Team
      url: /Team
      blank: false
    - title: Fundings
      url: /fundings
      blank: false
  section1:
    title: The bdverse 
    subtitle: A family of R packages for biodiversity data.
    tiles:
    - title: Standardize
      icon: bddwc
      text: Standardize Darwin Core (DwC) Field Names
      url: /bddwc
      buttonText: bddwc
    - title: Check
      icon: bdchecks
      text: Create, Filter, Perform, and Manage Data Quality Checks
      url: /bdchecks
      buttonText: bdchecks
    - title: Clean
      icon: bdclean
      text: User-friendly Workflows for Biodiversity Data Cleaning
      url: /bdclean
      buttonText: bdclean 
    - title: Explore
      icon: bdvis
      text: Interactive Biodiversity Data Visualizations & Dashboards 
      url: /
      buttonText: Coming Soon
  section2:
    title: More information
    subtitle: To get you started...
    features:
    - title: User Guide
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Take it for a spin & give us feedback 
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Developer Guide
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
    - title: Standing on the shoulders of giants
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Publications
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
      url: /publications
    - title: The Team
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: bdverse
    subtitle: b*iodiversity d*ata uni*verse
    buttonText: Try out bdverse now, in the comfort of your browser!
    buttonLink: "https://mybinder.org/v2/gh/bd-R/bdverse/master?urlpath=rstudio"
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/bd-R
      icon: github
      
    - link: https://bd-r-group.slack.com
      icon: slack
      
    - link: mailto:biodatr@gmail.com
      icon: google
      
    - link: https://hub.docker.com/u/bdverse
      icon: docker
    bulmalogo: false
    quicklinks:
      column2:
        title: ""
        links:
        - text: A Technion initiative
        - text: Built for supporting biodiversity science
        - text: ©bdverseTeam2019 | GPL3 | Blogdown | hugo-fresh theme
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

